# InsProbe参数
data_serial:
    port: "/dev/ttyUSB0"
    baudrate: 115200
    timeout: 1000 # 单位：ms

sync_serial:
    port: "/dev/ttyUSB1"
    baudrate: 115200
    timeout: 3000 # 单位：ms

sync_rate: 10 # 单位：Hz

# EVK4 HD参数
camera_label: "evk4_hd"
bias_file: "/home/ubuntu/Code/catkin_ws/src/dvs_sync/config/bias/evk4_hd.bias"
enable_event_rate_control: true # 是否启用事件速率控制
event_rate: 10000000 # 事件速率 单位：Ev/s
pub_rate: 100.0 # 事件发布频率 单位：Hz
pub_wrap_cost: false # 是否发布包装时间
use_multithread: true # 是否使用多线程包装事件
down_sample: 2 # 降采样倍数，为1时不降采样(要能被整除)

# 话题参数
events_topic: "/dvs/events"
imu_topic: "/dvs/imu"
offset_topic: "/dvs/offset"
events_size_topic: "/dvs/events_size"